### ISSUE TITLE
Allow `weakly_canonical` to be used with Windows long paths

### ISSUE THREAD

**Issue by emmenlau** [boostorg/filesystem#247] opened 2022-08-09 15:06 UTC
Currently I'm unable to call `weakly_canonical()` with a long path on Windows. Long path in this context means the Microsoft Windows extension described at https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation. A path can be prefixed by `\\?\` and then can have more than 260 characters (with a number of restrictions).

I could trace the problem of using long paths in `weakly_canonical()` to the method `create_file_handle()` in
https://github.com/boostorg/filesystem/blob/ea22e7655258b61776e4213ca4001a6b97b3541b/src/windows_tools.hpp#L259

This is called via: https://github.com/boostorg/filesystem/blob/ea22e7655258b61776e4213ca4001a6b97b3541b/src/operations.cpp#L4437

But the call fails for long paths. Since in `weakly_canonical()`, the handle is only needed for the root item, I could work around this by adding some extra handling to `create_file_handle()`. My added logic is:
 - If the given path has a long-path prefix but is less than 260 characters long, remove the long path prefix and rely on Windows to do the right thing.

Is that reasonable, and could something like this be added to the library?

**Comment by Lastique** [comment] 2022-08-09 15:48
If you need to operate on long paths on Windows, it is up to the application to prepend the path with `\\?\` prefix before passing to Boost.Filesystem. Boost.Filesystem does not do that for you, and I don't think I want to make it do so. Mostly because that would introduce unnecessary inefficiency and complicate implementation quite substantially.

**Comment by emmenlau** [comment] 2022-08-09 16:15
Dear @Lastique , thanks for the quick reply!

My problem is actually the opposite. I do have prepend the path with `\\?\` prefix before passing to Boost.Filesystem. This is causing the problem in https://github.com/boostorg/filesystem/blob/ea22e7655258b61776e4213ca4001a6b97b3541b/src/windows_tools.hpp#L259

**Comment by Lastique** [comment] 2022-08-09 16:22
I don't understand, what problem? Does the call fail with the `\\?\` prefix? With what error code? Can you prepare a small reproducer code?

Note that the prefix is only valid for absolute paths, so make sure you're not adding it if the path is relative.

**Comment by emmenlau** [comment] 2022-08-09 17:43
> I don't understand, what problem? Does the call fail with the `\\?\` prefix? With what error code? Can you prepare a small reproducer code?

I assumed that my description was more clear, sorry if it was not! The call of `::CreateFileW()` fails if the path has a prefix `\\?\`. In this case, the method `::CreateFileW()` returns a handle, but the handle seems to be all zeros. I'm not knowledgeable about Windows methods like `::CreateFileW()`, so I did not understand more than seeing that the handle is completely zero, and that seemed wrong. And subsequently `file_status head_status = detail::status_impl(head, &local_ec);` showed an error status.

As a test, I added code above `::CreateFileW()` that removes the prefix `\\?\`, and the error was gone. Therefore I conclude that `::CreateFileW()` does not support `\\?\`.

**Comment by emmenlau** [comment] 2022-08-09 17:47
So here is my workaround that fixes the problem for me:
```
diff --git a/libs/filesystem/src/windows_tools.hpp b/libs/filesystem/src/windows_tools.hpp
index 469be041e..e49ecd6a4 100644
--- a/libs/filesystem/src/windows_tools.hpp
+++ b/libs/filesystem/src/windows_tools.hpp
@@ -179,7 +179,11 @@ struct handle_wrapper
 //! Creates a file handle
 inline HANDLE create_file_handle(boost::filesystem::path const& p, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile = NULL)
 {
-    return ::CreateFileW(p.c_str(), dwDesiredAccess, dwShareMode, lpSecurityAttributes, dwCreationDisposition, dwFlagsAndAttributes, hTemplateFile);
+    std::wstring p_str = p.wstring();
+    if ((p_str.size() < 260) && (p_str.size() > 4) && (p_str[0] == L'\\') && (p_str[1] == L'\\') && (p_str[2] == L'?') && (p_str[3] == L'\\')) {
+        p_str = p_str.substr(4);
+    }
+    return ::CreateFileW(p_str.c_str(), dwDesiredAccess, dwShareMode, lpSecurityAttributes, dwCreationDisposition, dwFlagsAndAttributes, hTemplateFile);
 }
 
 } // namespace detail
```
I'm not saying that this is beautiful. But it just shows that there would be a way to avoid the problem.

**Comment by Lastique** [comment] 2022-08-09 18:14
[`CreateFileW`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilew) returns `INVALID_HANDLE_VALUE` on error, which is `(HANDLE)-1` (i.e. not zero). A zero returned handle is not considered an error.

**Comment by emmenlau** [comment] 2022-08-09 20:02
> Also, I asked about the error code and reproducer because this could give a clue as to what the problem is.

Yes, I understand that. I do not currently have access to a Windows machine, but I'll try to send more information when I have.

**Comment by Lastique** [comment] 2022-08-09 22:11
`CreateFileW` is [listed](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry) among the APIs that do support long paths. I have added a test to verify this.

I suspect the problem is with the path you're using. The `\\?\` prefix is not simply allowing for longer paths, it actually disables a great deal of path processing in Windows API. This means that the path must be absolute, must use backslashes as separators, and must not contain dot (".") and dot-dot ("..") elements. If you're using an UNC path then the prefix must be `\\?\UNC\` instead of `\\`. Please verify that the path you're passing to `weakly_canonical` meets these requirements.

**Comment by emmenlau** [comment] 2022-08-10 07:02
Thanks a lot for the follow-up!

What I can say so from my debugger session yesterday is that `weakly_canonical` was calling `CreateFileW` with only the head of the path in `file_status head_status = detail::status_impl(head, &local_ec);`. From what I recall from the debugger, the head of the path was something like `\\?\C:` and nothing else, maybe with one more backslash.

> Please verify that the path you're passing to `weakly_canonical` meets these requirements.

I have a method that takes care of these requirements before passing the path to `weakly_canonical`. It's possible that the method is buggy, but it did work for thousands of paths with `canonical`, and just failed for `weakly_canonical` so far. But I don't want to guess, so I'll try to reproduce the issue and let you know what I find!

**Comment by Lastique** [comment] 2022-08-10 10:31
> From what I recall from the debugger, the head of the path was something like `\\?\C:` and nothing else, maybe with one more backslash.

Yes, that was part of how `weakly_canonical` works, and this turned out to be the problem because the "C:" path is not absolute. I have committed a fix that should resolve this problem.

**Closed by Lastique** 2022-08-10 10:31 UTC

**Comment by emmenlau** [comment] 2022-08-10 12:40
But I see its fixed now, thanks!

**Comment by greenkalx** [comment] 2023-01-11 23:58
Was this fix meant to be promoted from?
`libs\filesystem\src\operations.cpp`
to
`boost\filesystem\operations.hpp`

I was expecting the fix in the latter, in 1_81_0.

We have three failing unit tests:
```
BOOST_CHECK(Path(R"(\\?\UNC\x\y)").IsUnc());
BOOST_CHECK(Path(R"(\\?\UNC\server\sharename\)").IsUnc());
BOOST_CHECK(Path(R"(\\?\UNC\x\y\s\z)").VolumeRoot() == LR"(\\?/UNC\x\y\)");
```

**Comment by Lastique** [comment] 2023-01-12 08:45
Yes, the fix is in Boost 1.81.0.

I'm not sure what unit tests you're running, they don't look like Boost.Filesystem. If you have a problem with Boost.Filesystem, please report it in a new issue, with a short reproducer.

**Comment by greenkalx** [comment] 2023-01-12 18:12
Thanks, I'll extract unit tests using only Boost and compare 1_65_1 with 1_81_0.

**Comment by greenkalx** [comment] 2023-01-13 02:13
Extracted tests that fail in 1_81_0 but pass with 1_65_1:

```
Path::iterator::difference_type const k_UncLongRootLen = 5;// min # of Path components
Path::iterator::difference_type const k_UncLongMarkerPos = 2;

{
	boost::filesystem::path zpath(R"(\\?\UNC\x\y)");
	BOOST_CHECK(std::distance(zpath.begin(), zpath.end()) >= k_UncLongRootLen);
	BOOST_CHECK(*zpath.begin() == LR"(\\?)");
	BOOST_CHECK(*std::next(zpath.begin(), k_UncLongMarkerPos) == LR"(UNC)");
}

{
	boost::filesystem::path zpath(R"(\\?\UNC\server\sharename\)");
	BOOST_CHECK(*zpath.begin() == LR"(\\?)");
	BOOST_CHECK(*std::next(zpath.begin(), k_UncLongMarkerPos) == LR"(UNC)");
}

{
	boost::filesystem::path zpath(R"(\\?\UNC\x\y\s\z)");
	BOOST_CHECK(*zpath.begin() == LR"(\\?)");
	BOOST_CHECK(*std::next(zpath.begin(), k_UncLongMarkerPos) == LR"(UNC)");
}
```
