### ISSUE TITLE
boost::filesystem is broken on Android since 1.74.0

### ISSUE THREAD

**Issue by andreya108** [boostorg/filesystem#183] opened 2021-04-02 16:25 UTC
Many operations (for example file_size) fail with an exception:

Exception runtime_error caught: boost::filesystem::status: Function not implemented

Can be easily reproduced.

boost 1.72.0 - works fine
boost 1.73.0 - works fine
boost 1.74.0 - fails
boost 1.75.0 - fails

Environment details:
Android NDK r22
Target android api level = 23
Target platform: aarch64

**Comment by Lastique** [comment] 2021-04-02 17:04
I suspect this is a duplicate of https://github.com/boostorg/filesystem/issues/172. Check if the Android version you're running matches the NDK version.

**Closed by Lastique** 2021-04-02 17:04 UTC

**Comment by andreya108** [comment] 2021-04-08 10:43
Definitely it matches, but the issue is real.
Fortunately, patch from #172 applied before build helps.
