### ISSUE TITLE
iOS build OK  But I null

### ISSUE THREAD

**Issue by zgbilltalent** [boostorg/filesystem#220] opened 2021-11-29 03:15 UTC
When I Use the Version of 1.77.0 in my app ，It will crash ，

 boost::filesystem::recursive_directory_iterator endIter;
    for (boost::filesystem::recursive_directory_iterator iter(p); iter != endIter; iter++) {
      if (boost::filesystem::is_directory(*iter)) {
          std::cout << "key:EEEEEE "  << std::endl;
          std::cout << iter->path().string() << std::endl;
          std::cout << "key:EEEEEE "  << std::endl;
      } else {
          std::cout << "is a file" << std::endl;
          std::cout << "key:EEEEEE "  << std::endl;
          std::cout << iter->path().string() << std::endl;
          std::cout << "key:EEEEEE "  << std::endl;
      }
    }

**Comment by Lastique** [comment] 2021-11-29 11:31
Can you provide more details? What's the backtrace? What does the filesystem tree look like?

**Comment by zgbilltalent** [comment] 2021-11-30 02:24
What should I do next? Re compile or something with my using way ?

**Comment by Lastique** [comment] 2021-11-30 10:55
I have no idea. You still haven't provided any details. Try debugging the problem on your end.

**Comment by zgbilltalent** [comment] 2021-11-30 11:16
How Can I give you the code ?zip?

**Comment by zgbilltalent** [comment] 2021-11-30 11:24
![1638271381699](https://user-images.githubusercontent.com/5159607/144038736-0fad1a12-f0ad-4687-ad41-d782ea18904f.jpg)
please Check it pic I upload

**Comment by zgbilltalent** [comment] 2021-11-30 11:24
What shuld I give it to you ？

**Comment by zgbilltalent** [comment] 2021-11-30 12:10
https://github.com/faithfracture/Apple-Boost-BuildScript this is the shell which I used to compile
version 1.77.0

**Comment by Lastique** [comment] 2021-11-30 12:23
From the backtrace it looks like the directory iterator is located at an invalid location (or `this` is an invalid pointer, which is more likely). This looks like either a compiler bug (miscompiled code) or some sort of ABI mismatch between your code and Boost compiled libraries.

In your Boost build scripts you're defining `BOOST_AC_USE_PTHREADS` and `BOOST_SP_USE_PTHREADS` [here](https://github.com/faithfracture/Apple-Boost-BuildScript/blob/7e30473420624ef98ff2713193a7a4d7aba6bfb3/boost.sh#L1587). Are you defining the same macros when you're compiling your own code? These macros affect ABI of atomic reference counters in smart pointers, including `intrusive_ptr` that is used in `directory_iterator` internally, and must be defined (or not defined) consistently when building Boost and your code.

Note that you should not need to define these macros. Boost.SmartPtr should detect an use a better implementation for atomic reference counters.

**Comment by zgbilltalent** [comment] 2021-11-30 13:01
https://github.com/faithfracture/Apple-Boost-BuildScript/issues/50 I think this is the problem

**Comment by Lastique** [comment] 2021-11-30 13:20
Closing as a duplicate of https://github.com/boostorg/filesystem/issues/147 then.

**Closed by Lastique** 2021-11-30 13:20 UTC
